// <auto-generated />
using System;
using GerenciamentoDeClientes.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GerenciamentoDeClientes.Infra.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210624005729_MapCliente")]
    partial class MapCliente
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GerenciamentoDeClientes.Domanin.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Bairro");

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Cep");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Cidade");

                    b.Property<string>("complementoEndereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ComplementoEndereco");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Cpf");

                    b.Property<DateTime>("dDataCadastro")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("dDataCadastro");

                    b.Property<DateTime>("dNascimento")
                        .HasColumnType("date")
                        .HasColumnName("dNascimento");

                    b.Property<bool>("deletado")
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nome");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("Sexo");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("UF");

                    b.HasKey("Id")
                        .HasName("idCliente");

                    b.ToTable("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
